"
I represent an Account object in a Salesforce org.
"
Class {
	#name : #Contact,
	#superclass : #SObject,
	#instVars : [
		'AccountId',
		'AssistantName',
		'AssistantPhone',
		'Birthdate',
		'CleanStatus',
		'OwnerId',
		'CreatedById',
		'Jigsaw',
		'Department',
		'Description',
		'DoNotCall',
		'Email',
		'HasOptedOutOfEmail',
		'Fax',
		'HasOptedOutOfFax',
		'HomePhone',
		'IndividualId',
		'Languages__c',
		'LastModifiedById',
		'LastCURequestDate',
		'LastCUUpdateDate',
		'LeadSource',
		'Level__c',
		'MailingAddress',
		'MobilePhone',
		'Name',
		'Salutation',
		'FirstName',
		'LastName',
		'OtherAddress',
		'OtherPhone',
		'Phone',
		'ReportsToId',
		'Title'
	],
	#category : #'Smallforce-Prefabs'
}

{ #category : #accessing }
Contact >> AccountId [

	^ AccountId
]

{ #category : #accessing }
Contact >> AccountId: anObject [

	AccountId := anObject
]

{ #category : #accessing }
Contact >> AssistantName [

	^ AssistantName
]

{ #category : #accessing }
Contact >> AssistantName: anObject [

	AssistantName := anObject
]

{ #category : #accessing }
Contact >> AssistantPhone [

	^ AssistantPhone
]

{ #category : #accessing }
Contact >> AssistantPhone: anObject [

	AssistantPhone := anObject
]

{ #category : #accessing }
Contact >> Birthdate [

	^ Birthdate
]

{ #category : #accessing }
Contact >> Birthdate: anObject [

	Birthdate := anObject
]

{ #category : #accessing }
Contact >> CleanStatus [

	^ CleanStatus
]

{ #category : #accessing }
Contact >> CleanStatus: anObject [

	CleanStatus := anObject
]

{ #category : #accessing }
Contact >> CreatedById [

	^ CreatedById
]

{ #category : #accessing }
Contact >> CreatedById: anObject [

	CreatedById := anObject
]

{ #category : #accessing }
Contact >> Department [

	^ Department
]

{ #category : #accessing }
Contact >> Department: anObject [

	Department := anObject
]

{ #category : #accessing }
Contact >> Description [

	^ Description
]

{ #category : #accessing }
Contact >> Description: anObject [

	Description := anObject
]

{ #category : #accessing }
Contact >> DoNotCall [

	^ DoNotCall
]

{ #category : #accessing }
Contact >> DoNotCall: anObject [

	DoNotCall := anObject
]

{ #category : #accessing }
Contact >> Email [

	^ Email
]

{ #category : #accessing }
Contact >> Email: anObject [

	Email := anObject
]

{ #category : #accessing }
Contact >> Fax [

	^ Fax
]

{ #category : #accessing }
Contact >> Fax: anObject [

	Fax := anObject
]

{ #category : #accessing }
Contact >> FirstName [

	^ FirstName
]

{ #category : #accessing }
Contact >> FirstName: anObject [

	FirstName := anObject
]

{ #category : #accessing }
Contact >> HasOptedOutOfEmail [

	^ HasOptedOutOfEmail
]

{ #category : #accessing }
Contact >> HasOptedOutOfEmail: anObject [

	HasOptedOutOfEmail := anObject
]

{ #category : #accessing }
Contact >> HasOptedOutOfFax [

	^ HasOptedOutOfFax
]

{ #category : #accessing }
Contact >> HasOptedOutOfFax: anObject [

	HasOptedOutOfFax := anObject
]

{ #category : #accessing }
Contact >> HomePhone [

	^ HomePhone
]

{ #category : #accessing }
Contact >> HomePhone: anObject [

	HomePhone := anObject
]

{ #category : #accessing }
Contact >> IndividualId [

	^ IndividualId
]

{ #category : #accessing }
Contact >> IndividualId: anObject [

	IndividualId := anObject
]

{ #category : #accessing }
Contact >> Jigsaw [

	^ Jigsaw
]

{ #category : #accessing }
Contact >> Jigsaw: anObject [

	Jigsaw := anObject
]

{ #category : #accessing }
Contact >> Languages__c [

	^ Languages__c
]

{ #category : #accessing }
Contact >> Languages__c: anObject [

	Languages__c := anObject
]

{ #category : #accessing }
Contact >> LastCURequestDate [

	^ LastCURequestDate
]

{ #category : #accessing }
Contact >> LastCURequestDate: anObject [

	LastCURequestDate := anObject
]

{ #category : #accessing }
Contact >> LastCUUpdateDate [

	^ LastCUUpdateDate
]

{ #category : #accessing }
Contact >> LastCUUpdateDate: anObject [

	LastCUUpdateDate := anObject
]

{ #category : #accessing }
Contact >> LastModifiedById [

	^ LastModifiedById
]

{ #category : #accessing }
Contact >> LastModifiedById: anObject [

	LastModifiedById := anObject
]

{ #category : #accessing }
Contact >> LastName [

	^ LastName
]

{ #category : #accessing }
Contact >> LastName: anObject [

	LastName := anObject
]

{ #category : #accessing }
Contact >> LeadSource [

	^ LeadSource
]

{ #category : #accessing }
Contact >> LeadSource: anObject [

	LeadSource := anObject
]

{ #category : #accessing }
Contact >> Level__c [

	^ Level__c
]

{ #category : #accessing }
Contact >> Level__c: anObject [

	Level__c := anObject
]

{ #category : #accessing }
Contact >> MailingAddress [

	^ MailingAddress
]

{ #category : #accessing }
Contact >> MailingAddress: anObject [

	MailingAddress := anObject
]

{ #category : #accessing }
Contact >> MobilePhone [

	^ MobilePhone
]

{ #category : #accessing }
Contact >> MobilePhone: anObject [

	MobilePhone := anObject
]

{ #category : #accessing }
Contact >> Name [

	^ Name
]

{ #category : #accessing }
Contact >> Name: anObject [

	Name := anObject
]

{ #category : #accessing }
Contact >> OtherAddress [

	^ OtherAddress
]

{ #category : #accessing }
Contact >> OtherAddress: anObject [

	OtherAddress := anObject
]

{ #category : #accessing }
Contact >> OtherPhone [

	^ OtherPhone
]

{ #category : #accessing }
Contact >> OtherPhone: anObject [

	OtherPhone := anObject
]

{ #category : #accessing }
Contact >> OwnerId [

	^ OwnerId
]

{ #category : #accessing }
Contact >> OwnerId: anObject [

	OwnerId := anObject
]

{ #category : #accessing }
Contact >> Phone [

	^ Phone
]

{ #category : #accessing }
Contact >> Phone: anObject [

	Phone := anObject
]

{ #category : #accessing }
Contact >> ReportsToId [

	^ ReportsToId
]

{ #category : #accessing }
Contact >> ReportsToId: anObject [

	ReportsToId := anObject
]

{ #category : #accessing }
Contact >> Salutation [

	^ Salutation
]

{ #category : #accessing }
Contact >> Salutation: anObject [

	Salutation := anObject
]

{ #category : #accessing }
Contact >> Title [

	^ Title
]

{ #category : #accessing }
Contact >> Title: anObject [

	Title := anObject
]

{ #category : #initialization }
Contact >> initialize [

	"All SObjects require an API name which should be defined on initialization by the subclass of SObject."

	"You should define read-only fields on the corresponding Salesforce object here by adding them to readOnlyFields."

	self apiName: 'Contact'.
	self readOnlyFields: #( 'CreatedById' 'LastModifiedById' )
]
