"
I represent an Contact object in a Salesforce org.

My fields conform to the API spec here: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_contact.htm
"
Class {
	#name : #Contact,
	#superclass : #SObject,
	#instVars : [
		'AccountId',
		'AssistantName',
		'AssistantPhone',
		'Birthdate',
		'CanAllowPortalSelfReg',
		'CleanStatus',
		'ConnectionReceivedId',
		'Department',
		'Description',
		'DoNotCall',
		'Email',
		'EmailBouncedDate',
		'EmailBouncedReason',
		'Fax',
		'FirstCallDateTime',
		'FirstEmailDateTime',
		'FirstName',
		'HasOptedOutOfEmail',
		'HasOptedOutOfFax',
		'HomePhone',
		'IndividualId',
		'IsDeleted',
		'IsEmailBounced',
		'IsPersonAccount',
		'Jigsaw',
		'LastActivityDate',
		'LastName',
		'LastReferencedDate',
		'LastViewedDate',
		'LeadSource',
		'MailingAddress',
		'MailingCity',
		'MailingCountry',
		'MailingCountryCode',
		'MailingGeocodeAccuracy',
		'MailingLatitude',
		'MailingLongitude',
		'MailingPostalCode',
		'MailingState',
		'MailingStateCode',
		'MailingStreet',
		'MasterRecordId',
		'MiddleName',
		'MobilePhone',
		'Name',
		'OtherAddress',
		'OtherCity',
		'OtherCountry',
		'OtherCountryCode',
		'OtherGeocodeAccuracy',
		'OtherLatitude',
		'OtherLongitude',
		'OtherPhone',
		'OtherPostalCode',
		'OtherState',
		'OtherStateCode',
		'OtherStreet',
		'OwnerId',
		'Phone',
		'PhotoUrl',
		'RecordTypeId',
		'ReportsToId',
		'Salutation',
		'Suffix',
		'Title'
	],
	#category : #'Smallforce-Prefabs-Base'
}

{ #category : #accessing }
Contact >> AccountId [

	^ AccountId
]

{ #category : #accessing }
Contact >> AccountId: anObject [

	AccountId := anObject
]

{ #category : #accessing }
Contact >> AssistantName [

	^ AssistantName
]

{ #category : #accessing }
Contact >> AssistantName: anObject [

	AssistantName := anObject
]

{ #category : #accessing }
Contact >> AssistantPhone [

	^ AssistantPhone
]

{ #category : #accessing }
Contact >> AssistantPhone: anObject [

	AssistantPhone := anObject
]

{ #category : #accessing }
Contact >> Birthdate [

	^ Birthdate
]

{ #category : #accessing }
Contact >> Birthdate: anObject [

	Birthdate := anObject
]

{ #category : #accessing }
Contact >> CanAllowPortalSelfReg [

	^ CanAllowPortalSelfReg
]

{ #category : #accessing }
Contact >> CanAllowPortalSelfReg: anObject [

	CanAllowPortalSelfReg := anObject
]

{ #category : #accessing }
Contact >> CleanStatus [

	^ CleanStatus
]

{ #category : #accessing }
Contact >> CleanStatus: anObject [

	CleanStatus := anObject
]

{ #category : #accessing }
Contact >> ConnectionReceivedId [

	^ ConnectionReceivedId
]

{ #category : #accessing }
Contact >> ConnectionReceivedId: anObject [

	ConnectionReceivedId := anObject
]

{ #category : #accessing }
Contact >> Department [

	^ Department
]

{ #category : #accessing }
Contact >> Department: anObject [

	Department := anObject
]

{ #category : #accessing }
Contact >> Description [

	^ Description
]

{ #category : #accessing }
Contact >> Description: anObject [

	Description := anObject
]

{ #category : #accessing }
Contact >> DoNotCall [

	^ DoNotCall
]

{ #category : #accessing }
Contact >> DoNotCall: anObject [

	DoNotCall := anObject
]

{ #category : #accessing }
Contact >> Email [

	^ Email
]

{ #category : #accessing }
Contact >> Email: anObject [

	Email := anObject
]

{ #category : #accessing }
Contact >> EmailBouncedDate [

	^ EmailBouncedDate
]

{ #category : #accessing }
Contact >> EmailBouncedDate: anObject [

	EmailBouncedDate := anObject
]

{ #category : #accessing }
Contact >> EmailBouncedReason [

	^ EmailBouncedReason
]

{ #category : #accessing }
Contact >> EmailBouncedReason: anObject [

	EmailBouncedReason := anObject
]

{ #category : #accessing }
Contact >> Fax [

	^ Fax
]

{ #category : #accessing }
Contact >> Fax: anObject [

	Fax := anObject
]

{ #category : #accessing }
Contact >> FirstCallDateTime [

	^ FirstCallDateTime
]

{ #category : #accessing }
Contact >> FirstCallDateTime: anObject [

	FirstCallDateTime := anObject
]

{ #category : #accessing }
Contact >> FirstEmailDateTime [

	^ FirstEmailDateTime
]

{ #category : #accessing }
Contact >> FirstEmailDateTime: anObject [

	FirstEmailDateTime := anObject
]

{ #category : #accessing }
Contact >> FirstName [

	^ FirstName
]

{ #category : #accessing }
Contact >> FirstName: anObject [

	FirstName := anObject
]

{ #category : #accessing }
Contact >> HasOptedOutOfEmail [

	^ HasOptedOutOfEmail
]

{ #category : #accessing }
Contact >> HasOptedOutOfEmail: anObject [

	HasOptedOutOfEmail := anObject
]

{ #category : #accessing }
Contact >> HasOptedOutOfFax [

	^ HasOptedOutOfFax
]

{ #category : #accessing }
Contact >> HasOptedOutOfFax: anObject [

	HasOptedOutOfFax := anObject
]

{ #category : #accessing }
Contact >> HomePhone [

	^ HomePhone
]

{ #category : #accessing }
Contact >> HomePhone: anObject [

	HomePhone := anObject
]

{ #category : #accessing }
Contact >> IndividualId [

	^ IndividualId
]

{ #category : #accessing }
Contact >> IndividualId: anObject [

	IndividualId := anObject
]

{ #category : #accessing }
Contact >> IsDeleted [

	^ IsDeleted
]

{ #category : #accessing }
Contact >> IsDeleted: anObject [

	IsDeleted := anObject
]

{ #category : #accessing }
Contact >> IsEmailBounced [

	^ IsEmailBounced
]

{ #category : #accessing }
Contact >> IsEmailBounced: anObject [

	IsEmailBounced := anObject
]

{ #category : #accessing }
Contact >> IsPersonAccount [

	^ IsPersonAccount
]

{ #category : #accessing }
Contact >> IsPersonAccount: anObject [

	IsPersonAccount := anObject
]

{ #category : #accessing }
Contact >> Jigsaw [

	^ Jigsaw
]

{ #category : #accessing }
Contact >> Jigsaw: anObject [

	Jigsaw := anObject
]

{ #category : #accessing }
Contact >> LastActivityDate [

	^ LastActivityDate
]

{ #category : #accessing }
Contact >> LastActivityDate: anObject [

	LastActivityDate := anObject
]

{ #category : #accessing }
Contact >> LastName [

	^ LastName
]

{ #category : #accessing }
Contact >> LastName: anObject [

	LastName := anObject
]

{ #category : #accessing }
Contact >> LastReferencedDate [

	^ LastReferencedDate
]

{ #category : #accessing }
Contact >> LastReferencedDate: anObject [

	LastReferencedDate := anObject
]

{ #category : #accessing }
Contact >> LastViewedDate [

	^ LastViewedDate
]

{ #category : #accessing }
Contact >> LastViewedDate: anObject [

	LastViewedDate := anObject
]

{ #category : #accessing }
Contact >> LeadSource [

	^ LeadSource
]

{ #category : #accessing }
Contact >> LeadSource: anObject [

	LeadSource := anObject
]

{ #category : #accessing }
Contact >> MailingAddress [

	^ MailingAddress
]

{ #category : #accessing }
Contact >> MailingAddress: anObject [

	MailingAddress := anObject
]

{ #category : #accessing }
Contact >> MailingCity [

	^ MailingCity
]

{ #category : #accessing }
Contact >> MailingCity: anObject [

	MailingCity := anObject
]

{ #category : #accessing }
Contact >> MailingCountry [

	^ MailingCountry
]

{ #category : #accessing }
Contact >> MailingCountry: anObject [

	MailingCountry := anObject
]

{ #category : #accessing }
Contact >> MailingCountryCode [

	^ MailingCountryCode
]

{ #category : #accessing }
Contact >> MailingCountryCode: anObject [

	MailingCountryCode := anObject
]

{ #category : #accessing }
Contact >> MailingGeocodeAccuracy [

	^ MailingGeocodeAccuracy
]

{ #category : #accessing }
Contact >> MailingGeocodeAccuracy: anObject [

	MailingGeocodeAccuracy := anObject
]

{ #category : #accessing }
Contact >> MailingLatitude [

	^ MailingLatitude
]

{ #category : #accessing }
Contact >> MailingLatitude: anObject [

	MailingLatitude := anObject
]

{ #category : #accessing }
Contact >> MailingLongitude [

	^ MailingLongitude
]

{ #category : #accessing }
Contact >> MailingLongitude: anObject [

	MailingLongitude := anObject
]

{ #category : #accessing }
Contact >> MailingPostalCode [

	^ MailingPostalCode
]

{ #category : #accessing }
Contact >> MailingPostalCode: anObject [

	MailingPostalCode := anObject
]

{ #category : #accessing }
Contact >> MailingState [

	^ MailingState
]

{ #category : #accessing }
Contact >> MailingState: anObject [

	MailingState := anObject
]

{ #category : #accessing }
Contact >> MailingStateCode [

	^ MailingStateCode
]

{ #category : #accessing }
Contact >> MailingStateCode: anObject [

	MailingStateCode := anObject
]

{ #category : #accessing }
Contact >> MailingStreet [

	^ MailingStreet
]

{ #category : #accessing }
Contact >> MailingStreet: anObject [

	MailingStreet := anObject
]

{ #category : #accessing }
Contact >> MasterRecordId [

	^ MasterRecordId
]

{ #category : #accessing }
Contact >> MasterRecordId: anObject [

	MasterRecordId := anObject
]

{ #category : #accessing }
Contact >> MiddleName [

	^ MiddleName
]

{ #category : #accessing }
Contact >> MiddleName: anObject [

	MiddleName := anObject
]

{ #category : #accessing }
Contact >> MobilePhone [

	^ MobilePhone
]

{ #category : #accessing }
Contact >> MobilePhone: anObject [

	MobilePhone := anObject
]

{ #category : #accessing }
Contact >> Name [

	^ Name
]

{ #category : #accessing }
Contact >> Name: anObject [

	Name := anObject
]

{ #category : #accessing }
Contact >> OtherAddress [

	^ OtherAddress
]

{ #category : #accessing }
Contact >> OtherAddress: anObject [

	OtherAddress := anObject
]

{ #category : #accessing }
Contact >> OtherCity [

	^ OtherCity
]

{ #category : #accessing }
Contact >> OtherCity: anObject [

	OtherCity := anObject
]

{ #category : #accessing }
Contact >> OtherCountry [

	^ OtherCountry
]

{ #category : #accessing }
Contact >> OtherCountry: anObject [

	OtherCountry := anObject
]

{ #category : #accessing }
Contact >> OtherCountryCode [

	^ OtherCountryCode
]

{ #category : #accessing }
Contact >> OtherCountryCode: anObject [

	OtherCountryCode := anObject
]

{ #category : #accessing }
Contact >> OtherGeocodeAccuracy [

	^ OtherGeocodeAccuracy
]

{ #category : #accessing }
Contact >> OtherGeocodeAccuracy: anObject [

	OtherGeocodeAccuracy := anObject
]

{ #category : #accessing }
Contact >> OtherLatitude [

	^ OtherLatitude
]

{ #category : #accessing }
Contact >> OtherLatitude: anObject [

	OtherLatitude := anObject
]

{ #category : #accessing }
Contact >> OtherLongitude [

	^ OtherLongitude
]

{ #category : #accessing }
Contact >> OtherLongitude: anObject [

	OtherLongitude := anObject
]

{ #category : #accessing }
Contact >> OtherPhone [

	^ OtherPhone
]

{ #category : #accessing }
Contact >> OtherPhone: anObject [

	OtherPhone := anObject
]

{ #category : #accessing }
Contact >> OtherPostalCode [

	^ OtherPostalCode
]

{ #category : #accessing }
Contact >> OtherPostalCode: anObject [

	OtherPostalCode := anObject
]

{ #category : #accessing }
Contact >> OtherState [

	^ OtherState
]

{ #category : #accessing }
Contact >> OtherState: anObject [

	OtherState := anObject
]

{ #category : #accessing }
Contact >> OtherStateCode [

	^ OtherStateCode
]

{ #category : #accessing }
Contact >> OtherStateCode: anObject [

	OtherStateCode := anObject
]

{ #category : #accessing }
Contact >> OtherStreet [

	^ OtherStreet
]

{ #category : #accessing }
Contact >> OtherStreet: anObject [

	OtherStreet := anObject
]

{ #category : #accessing }
Contact >> OwnerId [

	^ OwnerId
]

{ #category : #accessing }
Contact >> OwnerId: anObject [

	OwnerId := anObject
]

{ #category : #accessing }
Contact >> Phone [

	^ Phone
]

{ #category : #accessing }
Contact >> Phone: anObject [

	Phone := anObject
]

{ #category : #accessing }
Contact >> PhotoUrl [

	^ PhotoUrl
]

{ #category : #accessing }
Contact >> PhotoUrl: anObject [

	PhotoUrl := anObject
]

{ #category : #accessing }
Contact >> RecordTypeId [

	^ RecordTypeId
]

{ #category : #accessing }
Contact >> RecordTypeId: anObject [

	RecordTypeId := anObject
]

{ #category : #accessing }
Contact >> ReportsToId [

	^ ReportsToId
]

{ #category : #accessing }
Contact >> ReportsToId: anObject [

	ReportsToId := anObject
]

{ #category : #accessing }
Contact >> Salutation [

	^ Salutation
]

{ #category : #accessing }
Contact >> Salutation: anObject [

	Salutation := anObject
]

{ #category : #accessing }
Contact >> Suffix [

	^ Suffix
]

{ #category : #accessing }
Contact >> Suffix: anObject [

	Suffix := anObject
]

{ #category : #accessing }
Contact >> Title [

	^ Title
]

{ #category : #accessing }
Contact >> Title: anObject [

	Title := anObject
]

{ #category : #initialization }
Contact >> initialize [

	"All SObjects require an API name which should be defined on initialization by the subclass of SObject."

	"You should define read-only fields on the corresponding Salesforce object here by adding them to excludedFields."

	self apiName: 'Contact'.
	self excludedFields:
		#( 'CreatedById' 'LastModifiedById' 'CanAllowPortalSelfReg'
		   'ConnectionReceivedId' 'DoNotCall' 'FirstCallDateTime'
		   'FirstEmailDateTime' 'HasOptedOutOfEmail' 'HasOptedOutOfFax'
		   'IsDeleted' 'IsEmailBounced' 'IsPersonAccount' 'LastActivityDate'
		   'LastReferencedDate' 'LastViewedDate' 'MailingAddress'
		   'MailingCountryCode' 'MailingStateCode' 'MasterRecordId'
		   'MiddleName' 'Name' 'OtherAddress' 'OtherCountryCode'
		   'OtherStateCode' 'PhotoUrl' 'RecordTypeId' 'Suffix' )
]
