"
I represent an Pricebook2 object in a Salesforce org.

My fields conform to the API spec here: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_product2.htm
"
Class {
	#name : #Product2,
	#superclass : #SObject,
	#instVars : [
		'BillingPolicyId',
		'CanUseQuantitySchedule',
		'CanUseRevenueSchedule',
		'ConnectionReceivedId',
		'ConnectionSentId',
		'ConfigureDuringSale',
		'CurrencyIsoCode',
		'Description',
		'DisplayUrl',
		'ExternalDatSourceId',
		'ExternalId',
		'Family',
		'IsActive',
		'IsArchived',
		'IsDeleted',
		'IsSerialized',
		'IsSoldOnlyWithOtherProds',
		'LastReferencedDate',
		'LastViewedDate',
		'Name',
		'NumberOfQuantityInstallments',
		'NumberOfRevenueInstallments',
		'ProductClass',
		'ProductCode',
		'QuantityInstallmentPeriod',
		'QuantityScheduleType',
		'QuantityUnitOfMeasure',
		'RecalculateTotalPrice',
		'RevenueInstallentPeriod',
		'RevenueScheduleType',
		'StockKeepingUnit',
		'TaxPolicyId',
		'TransferRecordMode',
		'Type'
	],
	#category : #'Smallforce-Prefabs-Base'
}

{ #category : #accessing }
Product2 >> BillingPolicyId [

	^ BillingPolicyId
]

{ #category : #accessing }
Product2 >> BillingPolicyId: anObject [

	BillingPolicyId := anObject
]

{ #category : #accessing }
Product2 >> CanUseQuantitySchedule [

	^ CanUseQuantitySchedule
]

{ #category : #accessing }
Product2 >> CanUseQuantitySchedule: anObject [

	CanUseQuantitySchedule := anObject
]

{ #category : #accessing }
Product2 >> CanUseRevenueSchedule [

	^ CanUseRevenueSchedule
]

{ #category : #accessing }
Product2 >> CanUseRevenueSchedule: anObject [

	CanUseRevenueSchedule := anObject
]

{ #category : #accessing }
Product2 >> ConfigureDuringSale [

	^ ConfigureDuringSale
]

{ #category : #accessing }
Product2 >> ConfigureDuringSale: anObject [

	ConfigureDuringSale := anObject
]

{ #category : #accessing }
Product2 >> ConnectionReceivedId [

	^ ConnectionReceivedId
]

{ #category : #accessing }
Product2 >> ConnectionReceivedId: anObject [

	ConnectionReceivedId := anObject
]

{ #category : #accessing }
Product2 >> ConnectionSentId [

	^ ConnectionSentId
]

{ #category : #accessing }
Product2 >> ConnectionSentId: anObject [

	ConnectionSentId := anObject
]

{ #category : #accessing }
Product2 >> CurrencyIsoCode [

	^ CurrencyIsoCode
]

{ #category : #accessing }
Product2 >> CurrencyIsoCode: anObject [

	CurrencyIsoCode := anObject
]

{ #category : #accessing }
Product2 >> Description [

	^ Description
]

{ #category : #accessing }
Product2 >> Description: anObject [

	Description := anObject
]

{ #category : #accessing }
Product2 >> DisplayUrl [

	^ DisplayUrl
]

{ #category : #accessing }
Product2 >> DisplayUrl: anObject [

	DisplayUrl := anObject
]

{ #category : #accessing }
Product2 >> ExternalDatSourceId [

	^ ExternalDatSourceId
]

{ #category : #accessing }
Product2 >> ExternalDatSourceId: anObject [

	ExternalDatSourceId := anObject
]

{ #category : #accessing }
Product2 >> ExternalId [

	^ ExternalId
]

{ #category : #accessing }
Product2 >> ExternalId: anObject [

	ExternalId := anObject
]

{ #category : #accessing }
Product2 >> Family [

	^ Family
]

{ #category : #accessing }
Product2 >> Family: anObject [

	Family := anObject
]

{ #category : #accessing }
Product2 >> IsActive [

	^ IsActive
]

{ #category : #accessing }
Product2 >> IsActive: anObject [

	IsActive := anObject
]

{ #category : #accessing }
Product2 >> IsArchived [

	^ IsArchived
]

{ #category : #accessing }
Product2 >> IsArchived: anObject [

	IsArchived := anObject
]

{ #category : #accessing }
Product2 >> IsDeleted [

	^ IsDeleted
]

{ #category : #accessing }
Product2 >> IsDeleted: anObject [

	IsDeleted := anObject
]

{ #category : #accessing }
Product2 >> IsSerialized [

	^ IsSerialized
]

{ #category : #accessing }
Product2 >> IsSerialized: anObject [

	IsSerialized := anObject
]

{ #category : #accessing }
Product2 >> IsSoldOnlyWithOtherProds [

	^ IsSoldOnlyWithOtherProds
]

{ #category : #accessing }
Product2 >> IsSoldOnlyWithOtherProds: anObject [

	IsSoldOnlyWithOtherProds := anObject
]

{ #category : #accessing }
Product2 >> LastReferencedDate [

	^ LastReferencedDate
]

{ #category : #accessing }
Product2 >> LastReferencedDate: anObject [

	LastReferencedDate := anObject
]

{ #category : #accessing }
Product2 >> LastViewedDate [

	^ LastViewedDate
]

{ #category : #accessing }
Product2 >> LastViewedDate: anObject [

	LastViewedDate := anObject
]

{ #category : #accessing }
Product2 >> Name [

	^ Name
]

{ #category : #accessing }
Product2 >> Name: anObject [

	Name := anObject
]

{ #category : #accessing }
Product2 >> NumberOfQuantityInstallments [

	^ NumberOfQuantityInstallments
]

{ #category : #accessing }
Product2 >> NumberOfQuantityInstallments: anObject [

	NumberOfQuantityInstallments := anObject
]

{ #category : #accessing }
Product2 >> NumberOfRevenueInstallments [

	^ NumberOfRevenueInstallments
]

{ #category : #accessing }
Product2 >> NumberOfRevenueInstallments: anObject [

	NumberOfRevenueInstallments := anObject
]

{ #category : #accessing }
Product2 >> ProductClass [

	^ ProductClass
]

{ #category : #accessing }
Product2 >> ProductClass: anObject [

	ProductClass := anObject
]

{ #category : #accessing }
Product2 >> ProductCode [

	^ ProductCode
]

{ #category : #accessing }
Product2 >> ProductCode: anObject [

	ProductCode := anObject
]

{ #category : #accessing }
Product2 >> QuantityInstallmentPeriod [

	^ QuantityInstallmentPeriod
]

{ #category : #accessing }
Product2 >> QuantityInstallmentPeriod: anObject [

	QuantityInstallmentPeriod := anObject
]

{ #category : #accessing }
Product2 >> QuantityScheduleType [

	^ QuantityScheduleType
]

{ #category : #accessing }
Product2 >> QuantityScheduleType: anObject [

	QuantityScheduleType := anObject
]

{ #category : #accessing }
Product2 >> QuantityUnitOfMeasure [

	^ QuantityUnitOfMeasure
]

{ #category : #accessing }
Product2 >> QuantityUnitOfMeasure: anObject [

	QuantityUnitOfMeasure := anObject
]

{ #category : #accessing }
Product2 >> RecalculateTotalPrice [

	^ RecalculateTotalPrice
]

{ #category : #accessing }
Product2 >> RecalculateTotalPrice: anObject [

	RecalculateTotalPrice := anObject
]

{ #category : #accessing }
Product2 >> RevenueInstallentPeriod [

	^ RevenueInstallentPeriod
]

{ #category : #accessing }
Product2 >> RevenueInstallentPeriod: anObject [

	RevenueInstallentPeriod := anObject
]

{ #category : #accessing }
Product2 >> RevenueScheduleType [

	^ RevenueScheduleType
]

{ #category : #accessing }
Product2 >> RevenueScheduleType: anObject [

	RevenueScheduleType := anObject
]

{ #category : #accessing }
Product2 >> StockKeepingUnit [

	^ StockKeepingUnit
]

{ #category : #accessing }
Product2 >> StockKeepingUnit: anObject [

	StockKeepingUnit := anObject
]

{ #category : #accessing }
Product2 >> TaxPolicyId [

	^ TaxPolicyId
]

{ #category : #accessing }
Product2 >> TaxPolicyId: anObject [

	TaxPolicyId := anObject
]

{ #category : #accessing }
Product2 >> TransferRecordMode [

	^ TransferRecordMode
]

{ #category : #accessing }
Product2 >> TransferRecordMode: anObject [

	TransferRecordMode := anObject
]

{ #category : #accessing }
Product2 >> Type [

	^ Type
]

{ #category : #accessing }
Product2 >> Type: anObject [

	Type := anObject
]

{ #category : #initialization }
Product2 >> initialize [

	"All SObjects require an API name which should be defined on initialization by the subclass of SObject."

	"You should define read-only fields on the corresponding Salesforce object here by adding them to excludedFields."

	self apiName: 'Product2'.
	self excludedFields:
		#( 'BillingPolicyId' 'CanUseQuantitySchedule'
		   'CanUseRevenueSchedule' 'ConfigureDuringSale'
		   'ConnectionReceivedId' 'ConnectionSentId' 'CurrencyIsoCode'
		   'ExternalDatSourceId' 'IsArchived' 'IsDeleted' 'IsSerialized'
		   'IsSoldOnlyWithOtherProds' 'LastReferencedDate'
		   'LastViewedDate' 'NumberOfQuantityInstallments'
		   'NumberOfRevenueInstallments' 'ProductClass' 'QuantityInstallmentPeriod'
		   'QuantityScheduleType' 'RecalculateTotalPrice'
		   'RevenueInstallentPeriod' 'RevenueScheduleType'
		   'TaxPolicyId' 'TransferRecordMode' 'Type' )
]
