Class {
	#name : #SmallforceTest,
	#superclass : #TestCase,
	#category : #'Smallforce-Tests-Base'
}

{ #category : #test }
SmallforceTest >> testDescribeGlobal [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testDescribeGlobalIfModifiedSince [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testDescribeGlobalIfUnmodifiedSince [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testDescribeObject [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testGetObjectChangesSince [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testGetObjectMetadata [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testLimits [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testNewRequest [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testResourcesByVersion [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
SmallforceTest >> testVersions [

	self flag: #toImplement.
	self assert: false
]
